title: Bbbase
description: A style guide generator built using [Jekyll](http://jekyllrb.com/) and a good place to start designing your site.

# Makes for a cleaner file structure
source: src/
destination: _build

# Exclude some common files and include things like .htaccess
exclude: [README.md, node_modules, Gruntfile.js, package.json, deploy-stage, deploy-prod]
include: [.htaccess]

# Jekyll defaults
permalink: :title
sass:
    sass_dir: _sass
    style: expanded

# Collections
collections:
    elements:
        output: false
    forms:
        output: false
    patterns:
        output: false
